# name: Symfony Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up PHP
#         uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
#         with:
#           php-version: '8.2'

#       - name: Install dependencies
#         run: composer install --no-interaction --prefer-dist

#       - name: Run PHPUnit tests
#         run: php bin/phpunit
